services:
  icloud-api-go:
    image: shogoki/icloud-api-go
    build:
      context: .. 
      dockerfile: api/Dockerfile
    environment:
      PORT: 80
    ports:
      - "8000:80"
    networks:
      default:
      web:

networks:
    web:
       external:
           name: webproxy
